### ISSUE TITLE
There is no /lib folder

### ISSUE THREAD

**Issue by d0ruk** [domagojk/redux-orchestrate#1]
Hello,

The package I get from the registry does not come with a /lib folder.

**Comment by domagojk** [comment]
Well, that's embarrassing :sweat_smile:

I really don't understand why `lib` folder was not published.
Is "lib" a special kind of directory that npm recognizes and handles differently? I'm certain the folder was present before I used `npm publish`.

Anyway, I got it to work by renaming "lib" to "dist", thank you for pointing this out!

**Comment by domagojk** [comment]
Oh, the problem occurred because I forgot to define `.npmignore` :flushed:
