### ISSUE TITLE
What about Infinite event loop?

### ISSUE THREAD

**Issue by kulakowka** [domagojk/redux-orchestrate#3]
How do you solve the problem of an infinite loop? For example:

```javascript
const processManager = [
  {
    case: [ACTION_A],
    dispatch: ACTION_B
  },
 {
    case: [ACTION_B],
    dispatch: ACTION_A
  }
]
```

**Comment by domagojk** [comment]
Well It's up to you to solve it.

You can for example define dispatch as a function and return an action only if some condition is met.
Check [more complex logic section](https://github.com/domagojk/redux-orchestrate#more-complex-logic) for examples.
